name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create Release Archive
      run: |
        # Create release directory
        mkdir -p medextract-release
        
        # Copy essential files
        cp -r backend medextract-release/
        cp -r frontend medextract-release/
        cp -r docs medextract-release/
        cp -r installer medextract-release/
        cp docker-compose*.yml medextract-release/
        cp README.md medextract-release/
        cp LICENSE medextract-release/
        cp .env.example medextract-release/
        cp .gitignore medextract-release/
        
        # Create archives
        zip -r medextract-${{ github.ref_name }}.zip medextract-release
        tar -czf medextract-${{ github.ref_name }}.tar.gz medextract-release
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: MedExtract ${{ github.ref_name }}
        body: |
          # MedExtract ${{ github.ref_name }}
          
          ## Installation
          
          ### Windows Users
          1. Download `MEDEXTRACT-INSTALL.bat`
          2. Right-click and select "Run as administrator"
          3. Follow the installation prompts
          
          ### Manual Installation
          1. Download the source archive
          2. Extract to desired location
          3. Run `docker-compose build` and `docker-compose up`
          
          ## What's Included
          - Complete MedExtract application
          - Windows installer for easy setup
          - Documentation and user guides
          - Docker configuration files
          
          ## Requirements
          - Windows 10/11 (64-bit)
          - Docker Desktop
          - 16GB RAM minimum
          - 50GB free disk space
          
          See [Installation Guide](docs/INSTALLATION.md) for detailed instructions.
        files: |
          installer/MEDEXTRACT-INSTALL.bat
          medextract-${{ github.ref_name }}.zip
          medextract-${{ github.ref_name }}.tar.gz
        draft: false
        prerelease: false